mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^wiki/', include('wiki.urls', namespace="wiki")),
    url(r'^admin/', include(admin.site.urls)),
)

wiki/urls.py
from django.conf.urls import patterns, url

from wiki import views

urlpatterns = patterns('',
   url(r'^$', views.Index, name='index'),
   url(r'^(?P<title>[a-zA-Z0-9_-]+)/edit/$', views.EditPage, name='editpage'),
   url(r'^(?P<title>[a-zA-Z0-9_-]+)/history/$', views.HistoryPage, name='historypage'),
   url(r'^(?P<title>[a-zA-Z0-9_-]+)/$', views.WikiPage, name='wikipage'),
)

wiki/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.forms import ModelForm


class Page(models.Model):
    title = models.CharField(max_length=200)
    content =  models.TextField()
    pub_date = models.DateTimeField("Date published", auto_now_add = True)
    choices = (
        ('CH', 'Character'),
        ('FA', 'Faction'),
        ('EV', 'Event'),
        ('TC', 'Technology'),
        ('LC', 'Location'),
        ('MS', 'Miscellaneous'),
    )
    category = models.CharField(max_length=2,
                                      choices=choices,
                                      default='MS')

    def full_title(self):
        return self.title.replace("_"," ")

    def __str__(self):
        return self.full_title()[:99] + ": " + self.get_category_display() + ": " + self.content[:99]
    
    @classmethod
    def get_history(cls, path):
        return cls.objects.filter(title__iexact=path).distinct().order_by('-pub_date')
    
    @classmethod
    def get_latest(cls, path):
        return cls.objects.filter(title__iexact=path).distinct().latest('pub_date')

    @classmethod
    def get_by_id(cls, path, ver):
        return cls.objects.filter(title__iexact=path).distinct().get(id=ver)


class PageForm(ModelForm):
    class Meta:
        model = Page
        fields = ['category', 'content']

    
##
##def ver_check(v, path):
##    p = None
##    if v:
##        if v.isdigit():
##            p = Page.by_id(int(v), path)
##
##        if not p:
##            return None
##    else:
##        p = Page.by_path(path).get()
##    return p

wiki/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse

from wiki.models import Page, PageForm

def Index(request):
  latest_added_pages = Page.objects.order_by('-pub_date')[:20]
  context = {'latest_added_pages': latest_added_pages}
  return render(request, 'wiki/index.html', context)

def WikiPage(request, title):
  try:
    page = Page.objects.get(title=title)
    return render(request, 'wiki/page.html', {'page': page})
  except Page.DoesNotExist:
    return HttpResponseRedirect(reverse('wiki:editpage', args=(title,)))

def EditPage(request, title):
  try:
    page = Page.objects.get(title=title)
  except Page.DoesNotExist:
    page = Page(title=title, content="")


  if request.method == 'GET':
    form = PageForm(instance=page)
    return render(request, 'wiki/edit.html', {'page': page, 'form' : form})

  if request.method == 'POST':
    form = PageForm(request.POST, instance=page)
    form.save()
    #page.content = request.POST['content']
    #page.save()
    return HttpResponseRedirect(reverse('wiki:wikipage', args=(title,)))
    
  

def HistoryPage(request, title):
  page = get_object_or_404(Page, title=title)
  return render(request, 'wiki/page.html', {'page': page})






#########
##class Handler(webapp2.RequestHandler):
##  def write(self, *a, **kw):
##    self.response.out.write(*a, **kw)
##
##  def render(self, template, **kw):
##    t = jinja_env.get_template(template)
##    self.write(t.render(kw))
##        
##class EditPage(Handler):
##    def get(self, path):
##        username = None
##        user_cookie = self.request.cookies.get('user_id')
##        if user_cookie:
##            username = user_cookie.split('|')[0]
##            if check_secure_val(user_cookie) == username:
##                pass
##            else:
##                self.response.delete_cookie('user_id')
##                self.redirect("/login")
##        else:
##           self.redirect("/login")
##
##        v = self.request.get('v')
##        page = ver_check(v, path)
##
##        if page == None or page.content == None:
##            content = ''
##        else:
##            content = page.content
##        self.render("edit.html", username=username, url=path ,content=content)
##
##    def post(self, path):
##        content = self.request.get("content")
##        old_page = Page.by_path(path).get()
##
##        if not (old_page or content):
##            return
##        elif not old_page or old_page.content != content:
##            p = Page(parent = Page.parent_key(path), content = content)
##            p.put()
##            
##        self.redirect(path)
##
##class HistoryPage(Handler):
##    def get(self, path):
##        q = Page.by_path(path)
##        q.fetch(limit = 100)
##
##        posts = list(q)
##        if posts:
##            self.render("history.html", url = path, posts = posts)
##        else:
##            self.redirect("/_edit" + path)
##
##class WikiPage(Handler):
##    def get(self, path):
##        username = None
##        user_cookie = self.request.cookies.get('user_id')
##        if user_cookie:
##            username = user_cookie.split('|')[0]
##            if check_secure_val(user_cookie) == username:
##                pass
##            else:
##                self.response.delete_cookie('user_id')
##                username = None
##
##        v = self.request.get('v')
##        page = ver_check(v, path)      
##        
##        if page:
##            self.render("test.html", username=username, url=path, content=page.content)
##        else:
##            self.redirect("/_edit" + path)
##        
##
##class SignupHandler(Handler):
##
##    def get(self):
##        self.render("signup.html")
##
##    def post(self):
##        have_error = False
##        username = self.request.get('username')
##        password = self.request.get('password')
##        verify = self.request.get('verify')
##        email = self.request.get('email')
##
##        params = dict(username = username,
##                      email = email)
##
##        if not valid_username(username):
##            params['user_error'] = "That's not a valid username."
##            have_error = True
##
##        if not valid_password(password):
##            params['pass_error'] = "That wasn't a valid password."
##            have_error = True
##        elif password != verify:
##            params['verify_error'] = "Your passwords didn't match."
##            have_error = True
##
##        if not valid_email(email):
##            params['email_error'] = "That's not a valid email."
##            have_error = True
##
##        users = db.GqlQuery("select user_id from Users")
##        for user in users:
##            if username == user.user_id:
##                params['user_error'] = "That user already exists"
##                have_error = True
##
##        if have_error:
##            self.render("signup.html", **params)
##        else:
##            pwh = make_pw_hash(username, password)
##            u = Users(user_id=username, email=email, password=pwh)
##            u.put()
##
##            self.response.headers['Content-Type'] = 'text/plain'
##            user_cookie_str = self.request.cookies.get('user_id')
##            if user_cookie_str:
##                cookie_val = check_secure_val(user_cookie_str)
##                if cookie_val:
##                    self.redirect("/welcome")
##
##            new_user_val = make_secure_val(str(username))
##            self.response.headers.add_header('Set-Cookie', 'user_id=%s; Path=/' % new_user_val)
##            self.redirect("/")
##
##class LogIn(Handler):
##
##    def get(self):
##        self.render("login.html")
##
##    def post(self):
##        have_error = False
##        username = self.request.get('username')
##        password = self.request.get('password')
##        
##        checkUserName = Users.all()
##        checkUserName.filter('user_id', username)
##        userNameResult = checkUserName.get()
##
##        params ={}
##
##        if userNameResult:
##            pwh = userNameResult.password
##            if check_pw(username, password, pwh):
##                user_val = make_secure_val(str(username))
##                self.response.headers.add_header('Set-Cookie', 'user_id=%s; Path=/' % user_val)
##                self.redirect("/")
##            else:
##                params['invalid_login'] = "This is an invalid login."
##                self.render('login.html', **params)
##        else:
##            params['invalid_login'] = "This is an invalid login."
##            self.render('login.html', **params)
##            
##class LogOut(Handler):
##
##    def get(self):
##        self.response.delete_cookie('user_id')
##        self.redirect("/")

wiki/templates/wiki/edit.html
<html>
	<head>
		<title>{{ page.full_title }}</title>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'wiki/style.css' %}">
		<script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
		<script type="text/javascript">
		$( document ).ready(function() {
			var leftOffset = parseInt($("#sidebar").css('left'));
			$(window).scroll(function(){
	  			$('#sidebar').css('left',-$(window).scrollLeft() + leftOffset);
			});
		});
		</script>
	</head>
	<body>
		<div id="sidebar">
			<p><a href="{% url 'wiki:wikipage' page.title %}">{{ page.full_title }}</a></p>
			<ul>
				<li>
					<a href="{% url 'wiki:index' %}">Index</a>
				</li>
				<li>
					<a href="/admin">Admin</a>
				</li>
			</ul>
			<p id="sidecred"> Alex Carver 2015</p>
		</div>
		<div id="main">
			<h1 id="maintitle">{{ page.full_title }}</h1>
			<h3>{{ page.get_category_display }}</h3>
			<hr align="left" width="80%">
			{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
			<form action="{% url 'wiki:editpage' page.title %}" method="post">
				{% csrf_token %}
				{{ form.non_field_errors }}
				<div class="fieldWrapper">
					{{ form.category.errors }}
	    			<label for="{{ form.category.id_for_label }}">Category:</label><br/>
	    			{{ form.category }}
    			</div>
    			<div class="fieldWrapper">
	    			{{ form.content.errors }}
	    			<label for="{{ form.content.id_for_label }}">Content:</label><br/>
	    			{{ form.content }}
    			</div>
				<input type="submit" value="Save" />
			</form>
		</div>	
	</body>
<html>

wiki/templates/wiki/index.html
<html>
	<head>
		<title>Wiki Index</title>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'wiki/style.css' %}">
		<script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
		<script type="text/javascript">
		$( document ).ready(function() {
			var leftOffset = parseInt($("#sidebar").css('left'));
			$(window).scroll(function(){
	  			$('#sidebar').css('left',-$(window).scrollLeft() + leftOffset);
			});
		});
		</script>
	</head>
	<body>
		<div id="sidebar">
			<p>Index</p>
			<ul>
				<li>
					<a href="/admin">Admin</a>
				</li>
			</ul>
			<p id="sidecred"> Alex Carver 2015</p>
		</div>
		<div id="main">
			<h1>Front Page</h1>
			{% if latest_added_pages %}
			<p>Recently added pages:</p>
			    <ul>
			    {% for page in latest_added_pages %}
			        <li><a href="{% url 'wiki:wikipage' page.title %}">{{ page }}</a></li>
			    {% endfor %}
			    </ul>
			{% else %}
			    <p>No pages are available.</p>
			{% endif %}
		</div>
	</body>
<html>

wiki/templates/wiki/page.html
<html>
	<head>	
		<title>{{ page.full_title }}</title>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'wiki/style.css' %}" />
		<script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
		<script type="text/javascript">
		$( document ).ready(function() {
			var leftOffset = parseInt($("#sidebar").css('left'));
			$(window).scroll(function(){
	  			$('#sidebar').css('left',-$(window).scrollLeft() + leftOffset);
			});
		});
		</script>
	</head>
	<body>
		<div id="sidebar">
			<p>{{ page.full_title }}</p>
			<ul>
				<li>
					<a href="{% url 'wiki:editpage' page.title %}">Edit</a>
				</li>
				<li>
					<a href="{% url 'wiki:index' %}">Index</a>
				</li>
				<li>
					<a href="/admin">Admin</a>
				</li>
			</ul>
			<p id="sidecred"> Alex Carver 2015</p>
		</div>
		<div id="main">
			<h1 id="maintitle">{{ page.full_title }}</h1>
			<h3>{{ page.get_category_display }}</h3>
			<a href="{% url 'wiki:editpage' page.title %}" id="editlink">Edit</a>
			<hr align="left" width="80%">
			{% autoescape off %}
			<p>{{ page.content|linebreaks}}</p>
			{% endautoescape %}
		</div>
	</body>
<html>